service: node-serverless-package

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.15
  stage: ${env:STAGE}
  memorySize: 128

functions:
  hello:
    handler: handler.hello

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
